feat: Add Missing Methods for Execution details
novuhq/novu-elixir pull request #28
Opened 2023-10-10 04:00 UTC by sccalabr

Resolves #18

2023-10-10 16:21 UTC, doomspork commented
@sccalabr could you please address the failing CI checks?

2023-10-11 05:58 UTC, unicodeveloper commented
@sccalabr Please attend to the failing tests.

2023-10-17 21:49 UTC, btkostner requested changes

2023-10-17 21:49 UTC, btkostner commented on test/novu/execution_details_test.exs
> +      notification_group_name = "Test"
This variable is not used. Please remove it.

2023-10-19 07:24 UTC, unicodeveloper commented
@sccalabr All the CI tests are failing. Please look into it

2023-10-19 14:26 UTC, btkostner commented
The CI failures look to be coming from main branch. I'll open a PR soon to fix them

2023-10-19 19:45 UTC, btkostner requested changes
Code looks good. Just need to fix the [format error](https://github.com/novuhq/novu-elixir/actions/runs/6570062070/job/17875287484#step:6:13) in CI by running `mix format` and we should be good.

2023-10-20 13:11 UTC, doomspork approved these changes

2023-10-20 13:11 UTC, merged